### ISSUE TITLE
SSM package missing from Rocky 9

### ISSUE THREAD

**Issue by zam6ak** [system-storage-manager/ssm#13]
Perhaps not a an issue for project but `ssm` seems to be missing from Rocky Linux 9 (and from RHEL 9 also from the looks of it)....
But I cannot find any information in release notes or elsewhere as to why...

https://pkgs.org/download/system-storage-manager

Is this by design or... ?

Thanks

**Comment by zam6ak** [comment]
Ok... The following document for RHEL v9 does list `system-storage-manager` as a removed package...
https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/9/html-single/considerations_in_adopting_rhel_9/index#removed-packages_assembly_changes-to-packages

**Comment by lczerner** [comment]
Hi,

yes, you're correct. Unfortunately the project is no longer under active development and is not being actively maintained either. Based on that the package has been removed from RHEL9 and as a result it is missing in Rocky 9 as well.

**Comment by zam6ak** [comment]
Thanks for clarifying. @lczerner
