### ISSUE TITLE
Is this project abandoned?

### ISSUE THREAD

**Issue by q2dg** [system-storage-manager/ssm#2]
Last commit was made years ago.
Moreover, last Ubuntu versions have removed it from their repositories...
Any news?
Thanks!

**Comment by jtulak** [comment]
No, I took over, and I'm cleaning it a bit in the devel branch and need to
expand tests before I will make another release.

**Comment by q2dg** [comment]
Thanks.
I'll close this issue, then.
Anyway, the fact ssm isn't packaged in new versions of Ubuntu shouldn't be forgotten.

**Comment by jtulak** [comment]
Sure, thanks for the info, I'm opening a new issue about Ubuntu. (And sorry for the delay, I was travelling.)
