### ISSUE TITLE
make man in /doc failed

### ISSUE THREAD

**Issue by Sherlock-Holo** [system-storage-manager/ssm#5]
> ./generate_usage_includes.py
> Traceback (most recent call last):
>   File "./generate_usage_includes.py", line 9, in <module>
>     from ssmlib import main
>   File "/home/sherlock/git/AUR/system-storage-manager/src/ssm-system-storage-manager-1.2/doc/../ssmlib/main.py", line 27, in <module>
>     import pwquality
> ModuleNotFoundError: No module named 'pwquality'

**Comment by jtulak** [comment]
You are missing pwquality module. some distros have it as a package (pythonX-pwquality or something), for others it should be in pip.

**Comment by Sherlock-Holo** [comment]
on Arch Linux, libpwquality just only build for python2, I need to modify ssm to use python2, is there any problem will happen when ssm run on python2?

**Comment by Sherlock-Holo** [comment]
https://gist.github.com/Sherlock-Holo/09cb0e52d827b389d7e0a12a3b6072e5

**Comment by jtulak** [comment]
Python 2 is supported, there should be no issue.

**Comment by Sherlock-Holo** [comment]
> Traceback (most recent call last):
>   File "/usr/bin/ssm", line 59, in <module>
>     sys.exit(main.main())
>   File "/usr/lib/python2.7/site-packages/ssmlib/main.py", line 2863, in main
>     args.func(args)
>   File "/usr/lib/python2.7/site-packages/ssmlib/main.py", line 1989, in info
>     source.pinfo()
>   File "/usr/lib/python2.7/site-packages/ssmlib/main.py", line 1187, in pinfo
>     misc.ptable(node.get_printable_details())
>   File "/usr/lib/python2.7/site-packages/ssmlib/main.py", line 767, in get_printable_details
>     return self._get_printable_details()
>   File "/usr/lib/python2.7/site-packages/ssmlib/main.py", line 941, in _get_printable_details
>     pool = self.get_pool_node(self)
>   File "/usr/lib/python2.7/site-packages/ssmlib/main.py", line 680, in get_pool_node
>     alias = node.children[0].get_alias()
> IndexError: list index out of range
> 

when I run `sudo ssm info` it reports that

**Comment by jtulak** [comment]
Thanks for the info. Can I know what is your storage layout? Send me the output `lsblk` for the start. 

The command `ssm info` is experimental and still needs a lot of work to gather all the information, but it should not crash. (And I'm pretty sure that you would get the same issue with python3.)

**Comment by Sherlock-Holo** [comment]
> NAME                MAJ:MIN RM   SIZE RO TYPE MOUNTPOINT
> sda                   8:0    0 119.2G  0 disk 
> ├─sda1                8:1    0   260M  0 part /boot
> ├─sda2                8:2    0    16M  0 part 
> ├─sda3                8:3    0  85.6G  0 part 
> ├─sda4                8:4    0    12G  0 part 
> │ ├─SSD--pool-root  254:2    0    20G  0 lvm  /
> │ └─SSD--pool-speed 254:3    0  11.5G  0 lvm  /SSD_Storage/sherlock
> ├─sda5                8:5    0   893M  0 part 
> ├─sda6                8:6    0  19.5G  0 part 
> │ └─SSD--pool-root  254:2    0    20G  0 lvm  /
> └─sda7                8:7    0   980M  0 part 
> sdb                   8:16   0 931.5G  0 disk 
> ├─sdb1                8:17   0 788.1G  0 part 
> ├─sdb2                8:18   0  11.7G  0 part 
> ├─sdb3                8:19   0   100G  0 part 
> │ └─HDD--pool-home  254:1    0   100G  0 lvm  /home
> ├─sdb4                8:20   0  14.7G  0 part 
> │ └─HDD--pool-var   254:0    0  14.7G  0 lvm  /var
> └─sdb5                8:21   0    17G  0 part [SWAP]
>

**Comment by Sherlock-Holo** [comment]
I am sorry I have no idea to try on python3 because  Arch Linux makes a depend package  only build for py2, that is so why I have to build ssm on python2

**Comment by jtulak** [comment]
Mmm, I see nothing unusual in the layout that should cause an issue. What are the filesystems? (`lsblk --fs` can show it too.)

We will try to find at what device it is getting trashed. Can you change the line 680 in `/usr/lib/python2.7/site-packages/ssmlib/main.py`? Instead of the line `alias = node.children[0].get_alias()`, add this block of code:
```
                try:
                    alias = node.children[0].get_alias()
                except IndexError:
                    print(str(node))
                    return None
```
(Indentation is four spaces.) 

Run ssm again and show me the output.  With this change, instead of crash, ssm will skip some info-gathering about the offending volume/device, and will print out it's name and some other info. 

And thanks for helping me to find the bug. :-)

**Comment by Sherlock-Holo** [comment]
`lsblk --fs`

> NAME                FSTYPE      LABEL            UUID                                   MOUNTPOINT
> sda                                                                                     
> ├─sda1              vfat                         4C61-AFD2                              /boot
> ├─sda2                                                                                  
> ├─sda3              ntfs                         3288359088355397                       
> ├─sda4              LVM2_member                  PB5cKZ-Bj3B-ErqR-i8Ic-vmHh-1C2i-ocZDkc 
> │ ├─SSD--pool-root  btrfs                        673d4ca2-da0f-4f69-b4ea-92b053fa2894   /
> │ └─SSD--pool-speed xfs                          248d63fe-567f-4e8a-88c3-faf1b2d9d4a3   /SSD_Storage/sherlock
> ├─sda5              ntfs                         2E1E47D11E47912F                       
> ├─sda6              LVM2_member                  ktjucp-nhoe-W1Ct-VMc5-x9H5-BhfI-QomD8G 
> │ └─SSD--pool-root  btrfs                        673d4ca2-da0f-4f69-b4ea-92b053fa2894   /
> └─sda7              ntfs        Windows RE tools FE740E16740DD1F7                       
> sdb                                                                                     
> ├─sdb1              ntfs        DATA             06A09630A0962669                       
> ├─sdb2              ntfs        RECOVERY         48A698BEA698ADC6                       
> ├─sdb3              LVM2_member                  FYQ6ZF-hmkk-Ru0o-pg1r-6zco-TKVo-6jdWqn 
> │ └─HDD--pool-home  btrfs                        36babb36-09fb-49b2-85c8-0fe42da27418   /home
> ├─sdb4              LVM2_member                  l0MWQB-gBap-qdGl-bc5Q-VQup-DKOu-XCSeii 
> │ └─HDD--pool-var   xfs                          d90479c3-02b2-4ad9-b845-9c4e68f307a2   /var
> └─sdb5              swap                         e9df8f79-47c8-4926-980a-783010fab5f1   [SWAP]

when I modify line 680 it reports

> (set(['/dev/dm-1', '/dev/mapper/HDD--pool-home']), "{'pool_name': 'btrfs_HDD--pool-home', 'major': '254', 'hide': False, 'partitioned': 0, 'parent_name': '/dev/sdb3', 'vol_size': 104853504, 'dev_free': 48209428.48, 'dev_name': '/dev/dm-1', 'dev_used': '56644075.52', 'human_name': '/dev/mapper/HDD--pool-home', 'dev_size': 104853504, 'minor': '1'}")
> Traceback (most recent call last):
>   File "/usr/bin/ssm", line 59, in <module>
>     sys.exit(main.main())
>   File "/usr/lib/python2.7/site-packages/ssmlib/main.py", line 2868, in main
>     args.func(args)
>   File "/usr/lib/python2.7/site-packages/ssmlib/main.py", line 1994, in info
>     source.pinfo()
>   File "/usr/lib/python2.7/site-packages/ssmlib/main.py", line 1192, in pinfo
>     misc.ptable(node.get_printable_details())
>   File "/usr/lib/python2.7/site-packages/ssmlib/main.py", line 772, in get_printable_details
>     return self._get_printable_details()
>   File "/usr/lib/python2.7/site-packages/ssmlib/main.py", line 947, in _get_printable_details
>     out.append(('type', self.volume_type_name(pool['type'])))
> TypeError: 'NoneType' object has no attribute '__getitem__'

By the way, it should be `except IndexError` :p

**Comment by Sherlock-Holo** [comment]
```
(set(['/dev/dm-1', '/dev/mapper/HDD--pool-home']), "{'pool_name': 'btrfs_HDD--pool-home', 'major': '254', 'hide': False, 'partitioned': 0, 'parent_name': '/dev/sdb3', 'vol_size': 104853504, 'dev_free': 48209428.48, 'dev_name': '/dev/dm-1', 'dev_used': '56644075.52', 'human_name': '/dev/mapper/HDD--pool-home', 'dev_size': 104853504, 'minor': '1'}")
Traceback (most recent call last):
  File "/usr/bin/ssm", line 59, in <module>
    sys.exit(main.main())
  File "/usr/lib/python2.7/site-packages/ssmlib/main.py", line 2868, in main
    args.func(args)
  File "/usr/lib/python2.7/site-packages/ssmlib/main.py", line 1994, in info
    source.pinfo()
  File "/usr/lib/python2.7/site-packages/ssmlib/main.py", line 1192, in pinfo
    misc.ptable(node.get_printable_details())
  File "/usr/lib/python2.7/site-packages/ssmlib/main.py", line 772, in get_printable_details
    return self._get_printable_details()
  File "/usr/lib/python2.7/site-packages/ssmlib/main.py", line 947, in _get_printable_details
    out.append(('type', self.volume_type_name(pool['type'])))
TypeError: 'NoneType' object has no attribute '__getitem__'
```

this is a real log , github markdown change my log

**Comment by jtulak** [comment]
Thanks. I see it crashed anyway, but it printed the information I needed - and I have a reproducer now. I will let you know if I need anything else or when there is a fix.

**Comment by Sherlock-Holo** [comment]
thanks for your job

Jan Ťulák <notifications@github.com> 于 2018年9月26日周三 22:41写道：

**Comment by jtulak** [comment]
Hi @Sherlock-Holo 

I have created a patch for your issue. Do you still have the configuration available and can you try this fixed version? Just download ssm from branch [btrfs-info-fix](https://github.com/system-storage-manager/ssm/tree/btrfs-info-fix) and run the script at `bin/ssm.local` as you would run standard ssm.

Thanks!
Jan

**Comment by jtulak** [comment]
The patch for the original issue (that is, if pwquality is not present, ssm should still work) is in the mailing list and I will merge it together with a bunch of other patches in about two weeks after a review period.

**Comment by Sherlock-Holo** [comment]
I am sorry that I don't use ssm now and these days I have a lot of things to do so I can't test this patch
