### ISSUE TITLE
ssm list fail

### ISSUE THREAD

**Issue by davidmichea** [system-storage-manager/ssm#7]
Hi,

The last time I run ssm list, it worked well, but now I have a problem :

# ssm list
Traceback (most recent call last):
  File "/usr/bin/ssm", line 48, in <module>
    sys.exit(main.main())
  File "/usr/lib/python2.7/site-packages/ssmlib/main.py", line 2110, in main
    args.func(args)
  File "/usr/lib/python2.7/site-packages/ssmlib/main.py", line 1339, in list
    self.dev.ptable()
  File "/usr/lib/python2.7/site-packages/ssmlib/main.py", line 639, in ptable
    item = misc.humanize_size(data[attr])
  File "/usr/lib/python2.7/site-packages/ssmlib/misc.py", line 444, in humanize_size
    size = float(arg)
ValueError: invalid literal for float(): 148631552,00
[root@a2s-server-test ~]# uname -a
Linux ##################### 3.10.0-957.1.3.el7.x86_64 #1 SMP Thu Nov 29 14:49:43 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
[root@a2s-server-test ~]# ssm --version
ssm 0.4

Remark : the server is located in France (french locales use ',' instead of '.' in float numbers). But it has not moved since it was working.

If you need more informations or tests to run in-situ, please contact me at michea@unistra.fr

**Comment by jtulak** [comment]
Hi, thanks for the report.
I can replicate the issue, but I have absolutely no idea why the behaviour changed for you. Are you sure there was be no change in locale at the server, no system update that could change it?

**Comment by jtulak** [comment]
Fix (one line change) sent to mailing list for review: https://sourceforge.net/p/storagemanager/mailman/message/36593414/
